In [1]:
import numpy as np
from pathlib import Path

In [2]:
DATA_PATH = Path("/home/yujustin/tshirt_folding_yam/tshirt_hlm_yam_200/episode__74WVCdVIAJ64vh8xWjopT2HhoJEfepa1avZ6d5KUdw")

In [ ]:
act_left_pos = np.load(DATA_PATH / "action-left-pos.npy")
act_left_pos.shape

In [11]:
act_right_pos = np.load(DATA_PATH / "action-right-pos.npy")
act_right_pos.shape

(1620, 7)

In [5]:
left_gripper_pos = np.load(DATA_PATH / "left-gripper_pos.npy")
np.min(left_gripper_pos)

0.009775310902570371

In [18]:
left_joint_pos = np.load(DATA_PATH / "left-joint_pos.npy")
left_joint_pos.shape

(1620, 6)

In [ ]:
left_joint_pose = np.load(DATA_PATH / "left-joint_pose.npy") #EEF pose matrix
left_joint_pose[0]

array([[-0.29354959, -0.01747831,  0.95578405,  0.31028093],
       [-0.52771519,  0.83664394, -0.14677736, -0.03310749],
       [-0.79708552, -0.54746819, -0.25482005,  0.25573246],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [21]:
timestamp = np.load(DATA_PATH / "timestamp.npy")
timestamp.shape

(1620,)

In [ ]:
1620/(timestamp[-1] - timestamp[0]) #30 fps

29.827838355973217

In [3]:
import imageio.v3 as iio

In [25]:
video_frames = iio.imread(DATA_PATH / "top_camera-images-rgb.mp4", index=None)
video_frames.shape

(1620, 480, 848, 3)

In [26]:
from lerobot.common.datasets.lerobot_dataset import HF_LEROBOT_HOME

In [27]:
HF_LEROBOT_HOME

PosixPath('/home/kavishk/.cache/huggingface/lerobot')

In [29]:
act_left_pos == np.concatenate([left_joint_pos, left_gripper_pos], axis=1)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [30]:
act_left_pos[0]

array([-0.05522331,  0.74691802,  0.64352071, -0.08895686,  0.10110821,
       -0.5736953 ,  0.99014041])

In [31]:
left_joint_pos[0]

array([-0.05512322,  0.74864576,  0.64488441, -0.15506981,  0.09403372,
       -0.57698177])

In [1]:
from torchcodec.decoders import VideoDecoder

In [2]:
import os
print(os.environ.get('LD_LIBRARY_PATH', 'not set'))

not set


In [9]:

exo_decoder = VideoDecoder(DATA_PATH / "top_camera-images-rgb.mp4")

In [11]:
exo_decoder[0].shape

torch.Size([3, 480, 848])

In [6]:
import json
with open(DATA_PATH / "top_camera-images-rgb_annotation.json", "r") as f:
                annotations = json.load(f)

In [8]:
annotations["annotations"]

[{'from_frame': 0,
  'to_frame': 63,
  'label': 'grab crumpled tshirt from bin with the right arm',
  'type': 'segment',
  'id': 'mark_9dd72bc1-e044-4e46-86e9-db8e038e7775'},
 {'from_frame': 63,
  'to_frame': 98,
  'label': 'move the tshirt to the center of the board',
  'type': 'segment',
  'id': 'mark_3c782aa3-1870-4b40-8dd4-c24ee37874ac'},
 {'from_frame': 98,
  'to_frame': 737,
  'label': 'flatten out the tshirt',
  'type': 'segment',
  'id': 'mark_52f014c7-abb3-48c1-92f8-1eb85d36aad4'},
 {'from_frame': 737,
  'to_frame': 834,
  'label': 'grab the side of the flattened tshirt closest away from the robot with both arms',
  'type': 'segment',
  'id': 'mark_0a6e91cf-b93a-411c-8c9b-d61d3da968da'},
 {'from_frame': 834,
  'to_frame': 1075,
  'label': 'fold the flattened tshirt in 1/3 of the way',
  'type': 'segment',
  'id': 'mark_7df68e9e-b3ef-498f-ad4d-13aff88b08fa'},
 {'from_frame': 1075,
  'to_frame': 1163,
  'label': 'grab the side of the flattened tshirt furthest away from the robot

In [7]:
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset

In [9]:
dataset = LeRobotDataset("tshirt_mini")

Generating train split: 0 examples [00:00, ? examples/s]

In [10]:
dataset

LeRobotDataset({
    Repository ID: 'tshirt_mini',
    Number of selected episodes: '5',
    Number of selected samples: '12326',
    Features: '['exo_image', 'wrist_right_image', 'wrist_left_image', 'states', 'actions', 'eef_poses', 'prompt', 'timestamp', 'frame_index', 'episode_index', 'index', 'task_index']',
})',

In [11]:
dataset[2008]

{'exo_image': tensor([[[0.4824, 0.4824, 0.4824,  ..., 0.0000, 0.0000, 0.0000],
          [0.4824, 0.4824, 0.4824,  ..., 0.0000, 0.0000, 0.0000],
          [0.4824, 0.4824, 0.4824,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.4627, 0.4627, 0.4627,  ..., 0.0000, 0.0000, 0.0000],
          [0.4627, 0.4627, 0.4627,  ..., 0.0000, 0.0000, 0.0000],
          [0.4627, 0.4627, 0.4627,  ..., 0.0000, 0.0000, 0.0000]],
 
         [[0.4627, 0.4627, 0.4627,  ..., 0.0000, 0.0000, 0.0000],
          [0.4627, 0.4627, 0.4627,  ..., 0.0000, 0.0000, 0.0000],
          [0.4627, 0.4627, 0.4627,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.4471, 0.4471, 0.4471,  ..., 0.0000, 0.0000, 0.0000],
          [0.4471, 0.4471, 0.4471,  ..., 0.0000, 0.0000, 0.0000],
          [0.4471, 0.4471, 0.4471,  ..., 0.0000, 0.0000, 0.0000]],
 
         [[0.4784, 0.4784, 0.4784,  ..., 0.0000, 0.0000, 0.0000],
          [0.4784, 0.4784, 0.4784,  ..., 0.0000, 0.0000, 0.0000],
          [0.4784, 0.4784, 

In [4]:
import tqdm
for i in [56, 167, 279, 391]:
    try:
        dataset[i]
    except AssertionError as e:
        print(f"idx {i}:", e)

idx 56: One or several query timestamps unexpectedly violate the tolerance (tensor([0.0333]) > tolerance_s=0.0001).It means that the closest frame that can be loaded from the video is too far away in time.This might be due to synchronization issues with timestamps during data collection.To be safe, we advise to ignore this item during training.
queried timestamps: tensor([1.8667])
loaded timestamps: tensor([1.9000])
video: /home/kavishk/.cache/huggingface/lerobot/tshirt_combined3/videos/chunk-000/exo_image/episode_000000.mp4
idx 167: One or several query timestamps unexpectedly violate the tolerance (tensor([0.0333]) > tolerance_s=0.0001).It means that the closest frame that can be loaded from the video is too far away in time.This might be due to synchronization issues with timestamps during data collection.To be safe, we advise to ignore this item during training.
queried timestamps: tensor([5.5667])
loaded timestamps: tensor([5.6000])
video: /home/kavishk/.cache/huggingface/lerobot/

In [12]:
import tqdm
for i in tqdm.trange(len(dataset)):
    try:
        if dataset[i]["states"] is None:
            print(i)
    except:
        print(f"{i} errored")
    

100%|██████████| 12326/12326 [01:55<00:00, 106.27it/s]


In [13]:
import subprocess
result = subprocess.run(
    [
        "ffprobe", "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "packet=pts_time",
        "-of", "csv=p=0",
        "/home/kavishk/.cache/huggingface/lerobot/tshirt_test_single2/videos/chunk-000/exo_image/episode_000000.mp4",
    ],
    capture_output=True, text=True,
)
pts = [float(x) for x in result.stdout.strip().split("\n")]
print(f"Total frames: {len(pts)}")
print(f"First 5: {pts[:5]}")
print(f"Around frame 167: {pts[164:170]}")
print(f"Expected around 167: {[i/30 for i in range(164, 170)]}")

Total frames: 2275
First 5: [0.0, 0.033333, 0.066667, 0.1, 0.133333]
Around frame 167: [5.466667, 5.5, 5.533333, 5.6, 5.633333, 5.666667]
Expected around 167: [5.466666666666667, 5.5, 5.533333333333333, 5.566666666666666, 5.6, 5.633333333333334]
